# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeIndividualM2LL <- function(nObservedVariables, rawData, impliedMeans, impliedCovariance) {
    .Call(`_lessSEM_computeIndividualM2LL`, nObservedVariables, rawData, impliedMeans, impliedCovariance)
}

computeGroupM2LL <- function(sampleSize, nObservedVariables, observedMeans, observedCov, impliedMeans, impliedCovariance) {
    .Call(`_lessSEM_computeGroupM2LL`, sampleSize, nObservedVariables, observedMeans, observedCov, impliedMeans, impliedCovariance)
}

computeImpliedCovariance <- function(Fmatrix, Amatrix, Smatrix) {
    .Call(`_lessSEM_computeImpliedCovariance`, Fmatrix, Amatrix, Smatrix)
}

computeImpliedMeans <- function(Fmatrix, Amatrix, Mvector) {
    .Call(`_lessSEM_computeImpliedMeans`, Fmatrix, Amatrix, Mvector)
}

mcpPenalty_C <- function(par, lambda_p, theta) {
    .Call(`_lessSEM_mcpPenalty_C`, par, lambda_p, theta)
}

scadPenalty_C <- function(par, lambda_p, theta) {
    .Call(`_lessSEM_scadPenalty_C`, par, lambda_p, theta)
}

