# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    # every second month
  cron:
    '0 9 5 1,3,5,7,9,11 *'

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: macos-latest,   r: 'devel'}

          - {os: windows-latest, r: 'release'}

          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Install mxsem
        run: |
          # specify library location (copied from teichert at https://stackoverflow.com/questions/32540919/library-is-not-writable)
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)  # create personal library
          .libPaths(Sys.getenv("R_LIBS_USER"))  # add to the path
          install.packages("devtools")
          devtools::install_deps(".")
          devtools::install(pkg = ".")
        shell: Rscript {0}

      - name: testmxsem
        run: |
          cd ..
          mkdir testmxsem
          cd testmxsem
      - uses: actions/checkout@v2
        with:
          repository: 'jhorzek/testmxsem'
          ref: 'main'
      - name: Extended tests
        run: |
          install.packages("lavaan")
          install.packages("testthat")
          install.packages("devtools")
          devtools::build(pkg = ".", binary = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
