# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CMD check Windows and MacOS

on:
  workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})
    
    strategy:
      matrix:
        r-version: ['release']
        os: ['windows-latest', 'macOS-latest']

    steps:
      - name: create directory
        run: |
         mkdir lessSEM
         cd lessSEM
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install devtools
        run: |
         options(install.packages.compile.from.source = "never")
         install.packages(c("devtools", "remotes", "rcmdcheck"))
        shell: Rscript {0}
      - name: Install dependencies
        run: Rscript .github/workflows/install_dependencies_compliled.R
      - name: build and save as artifact
        run: devtools::build(pkg = ".", binary = TRUE)
        shell: Rscript {0}
      - name: upload package windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: windows_release
          path: D:/a/lessSEM/lessSEM_*.zip
      - name: upload package macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: macos_release
          path: /Users/runner/work/lessSEM/lessSEM_*.tgz       
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
      - name: lessTest
        run: |
         cd ..
         mkdir lessTest
         cd lessTest
      - uses: actions/checkout@v2
        with: 
         repository: 'jhorzek/lessTest'
      - name: Extended tests
        run: |
         devtools::build(pkg = ".", binary = TRUE)
         rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
