name: R CMD check ubuntu

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
  container:
   image: ghcr.io/jhorzek/lesssem_dependencies:latest
   credentials:
    username: ${{ github.actor }}
    password: ${{ secrets.CR_PAT }}
    
  steps:
    - uses: actions/checkout@v3
    - name: Install devtools
      run: Rscript suppressWarnings(install.packages('devtools'))
    - name: Check
      run: devtools::check(error_on = "warning", manual = FALSE)
      shell: Rscript {0}
      # If the test above did not fail, we will create a new release for the package:
    - name: Build package
      run: R CMD build .

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ github.ref }} (ubuntu)
        draft: false
        prerelease: false
        files: mypackage_*.tar.gz
