name: R CMD check ubuntu

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
  container:
   image: ghcr.io/jhorzek/lesssem_dependencies:latest
   credentials:
    username: ${{ github.actor }}
    password: ${{ secrets.CR_PAT }}
    
  steps:
    - uses: actions/checkout@v3
    - name: Install devtools
      run: install.packages("devtools")
      shell: Rscript {0}
    - name: build and save as artifact
      run: devtools::build(pkg = ".", binary = TRUE)
      shell: Rscript {0}
    - name: upload package
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu_release
        path: /__w/lessSEM/lessSEM_*.tar.gz
    - name: install package
      run: |
        devtools::install(pkg = ".")
      shell: Rscript {0}
    - name: Check
      run: rcmdcheck::rcmdcheck(pkg = ".", args = "--no-manual", error_on = "warning")
      shell: Rscript {0}
    - name: lessTest
      run: |
       cd ..
       mkdir lessTest
       cd lessTest
    - uses: actions/checkout@v2
      with: 
       repository: 'jhorzek/lessTest'
    - name: Extended tests
      run: |
       devtools::build(pkg = ".", binary = TRUE)
       rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
      shell: Rscript {0}
      
