name: R CMD as-cran check Windows

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-as-cran:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})

    strategy:
      matrix:
        r-version: ['release', 'devel']
        os: ['windows-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - run:
          choco install pandoc
      - uses: r-lib/actions/check-r-package@v2
