name: R CMD check extended

on:
  pull_request:
    branches: ["main", "development"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-as-cran:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})

    strategy:
      matrix:
        r-version: ['release']
        os: ['macOS-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: install compiled packages
        run: |
          install.packages(c(
            "devtools",
            "lavaan",
            "Rcpp",
            "RcppArmadillo",
            "RcppParallel",
            "ggplot2",
            "ggrepel",
            "tidyr",
            "stringr",
            "numDeriv",
            "utils",
            "stats",
            "graphics",
            "rlang",
            "mvtnor",
            "knitr",
            "plotly",
            "rmarkdown",
            "Rsolnp",
            "knitr",
            "plotly",
            "testthat",
            "glmnet",
            "ncvreg",
            "regsem",
            "lslx",
            "Matrix",
            "OpenMx",
            "ctsemOMX"))
        shell: Rscript {0}
      - name: Install lessSEM
        run: devtools::install(pkg = ".")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(path = ".", args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
      - name: lessTest
        run: |
          cd ..
          mkdir lessTest
          cd lessTest
      - uses: actions/checkout@v2
        with: 
          repository: 'jhorzek/lessTest'
          ref: 'development'
      - name: Extended tests
        run: |
          devtools::build(pkg = ".", binary = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
