name: R CMD check ubuntu

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
  container:
   image: ghcr.io/jhorzek/lesssem_dependencies:latest
   credentials:
    username: jhorzek
    password: ${{secrets.DOCKER}}
    
  steps:
    - uses: actions/checkout@v3
    - name: Check
      run: devtools::check(error_on = "warning", manual = FALSE)
      shell: Rscript {0}
