# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CMD check windows

on:
  workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})
    
    strategy:
      matrix:
        r-version: ['release']
        os: ['windows-latest'] # 'macOS-latest' -> add later on; running on macOS is more expensive

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          options(install.packages.compile.from.source = "never")
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: build and save as artifact
        run: devtools::build(pkg = ".", binary = TRUE)
        shell: Rscript {0}
      - name: upload package
        uses: actions/upload-artifact@v3
        with:
          name: windows_release
          path: mypackage_*.tar.gz
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
