name: R CMD as-cran check Windows

on:
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:
    # every second month
  cron:
    '0 9 5 1,3,5,7,9,11 *'

permissions:
  contents: read

jobs:
  check-as-cran:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})

    strategy:
      matrix:
        r-version: ['release', 'devel']
        os: ['windows-latest', 'macOS-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/check-r-package@v2
  
