name: Ubuntu release

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
  container:
   image: ghcr.io/jhorzek/lesssem_dependencies:latest
   credentials:
    username: ${{ github.actor }}
    password: ${{ secrets.CR_PAT }}
    
  steps:
    - uses: actions/checkout@v3
    - name: Install devtools
      run: install.packages("devtools")
      shell: Rscript {0}
      
    - name: Build package
      run: tools:::.build_packages(".")
      shell: Rscript {0}

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ github.ref }} (ubuntu)
        draft: false
        prerelease: false
        files: lessSEM_*.tar.gz
